/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import apumedicalcenter.Customer;
import apumedicalcenter.FeedbackDoctor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;

/**
 *
 * @author tatsu
 */
public class CustomerFeedbackDoctor extends javax.swing.JFrame {
    private DefaultTableModel model = new DefaultTableModel();
    private String[] columnName = {"Doctor ID","Doctor Name","Date","Comment"};
    private Customer customer;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerFeedbackDoctor.class.getName());

    public CustomerFeedbackDoctor(Customer customer) {
        this.customer=customer;
        initComponents();
        setTitle("Customer Comment Doctor");
        jTextField2.setEditable(false);
        model.setColumnIdentifiers(columnName);
        jTable1.setModel(model);
        setTitle("Customer Feedback (Doctor)");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        setupFocusListeners();
        loadCustomerDoctorFeedback();
        setupTableRowListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Customer Feedback (Doctor)");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Doctor ID:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Doctor Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Date:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Feedback:");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Back To Main Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel1)
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jButton1)
                                .addGap(34, 34, 34)
                                .addComponent(jButton2)))
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String docID = jTextField1.getText().trim().toUpperCase();
        String docName =  jTextField2.getText().trim();
        String comment = jTextField3.getText().trim();
        String date = "";
        
        
        if(jDateChooser1.getDate()!=null){
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            date = sdf.format(jDateChooser1.getDate());
        }
        
        if(docID.isEmpty()||docName.isEmpty()||date.isEmpty()||comment.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill in all the fields!");
            jTextField1.requestFocus();
            return;
        }
        
        FeedbackDoctor feedback = new FeedbackDoctor(
            customer.getId(),
            customer.getName(),
            docID,
            docName,
            date,
            comment
        );
        
        try(FileWriter w = new FileWriter ("CustomerFeedbackDoctor.txt",true)){
            w.write(feedback.toString() + System.lineSeparator());
            JOptionPane.showMessageDialog(this, "Feedback saved sucessfully");
            
            model.addRow(new Object[]{feedback.getDocID(), feedback.getDocName(), feedback.getDate(), feedback.getComment()});
            
            jTextField1.setText("");
            jTextField2.setText("");
            jDateChooser1.setDate(null); 
            jTextField3.setText("");
            jTextField1.requestFocus();  
            
            
        }catch (IOException e){
            JOptionPane.showMessageDialog(this, "Error saving feedback!");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a feedback to delete!");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete this feedback?", "Confirm Delete", 
            JOptionPane.YES_NO_OPTION);
        
        if (confirm != JOptionPane.YES_OPTION) return;
        
        String docID = model.getValueAt(selectedRow, 0).toString();
        String docName = model.getValueAt(selectedRow, 1).toString();
        String date = model.getValueAt(selectedRow, 2).toString();
        String comment = model.getValueAt(selectedRow, 3).toString();
        String cusID = customer.getId();
        String cusName = customer.getName();
        
        FeedbackDoctor feedback = new FeedbackDoctor(
            cusID, cusName, docID, docName, date, comment
        );
        
        model.removeRow(selectedRow);
        
        try{
            List<String> lines = new ArrayList<>();
            try (BufferedReader br = new BufferedReader(new FileReader("CustomerFeedbackDoctor.txt"))){
                String line;
                while ((line = br.readLine())!=null){
                    if (!line.equals(feedback.toString())){
                        lines.add(line);
                    }
                }
            }
            
            try(FileWriter w = new FileWriter("CustomerFeedbackDoctor.txt",false)){//false open the file in overwrite mode,not append.
                for (String l : lines){
                    w.write(l+System.lineSeparator());
                }
            }
            
            JOptionPane.showMessageDialog(this, "Feedback deleted successfully!");
            
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jDateChooser1.setDate(null);
            jTextField1.requestFocus();
            
        }catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error deleting feedback!");
        }     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CustomerMainMenu mainmenu = new CustomerMainMenu(customer);
        mainmenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        jTextField3.requestFocus();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void setupFocusListeners() {
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            
             @Override
             public void focusLost(java.awt.event.FocusEvent evt) {
                 autoDoctorIDtoName();
             }
        });
    }
    
    private void autoDoctorIDtoName(){
        String docID = jTextField1.getText().trim();
        
        if (docID.isEmpty()){
            jTextField2.setText("");
            return;
        }
        
        String docName = findDoctorName(docID);
        if(docName == null){
            JOptionPane.showMessageDialog(this, "Doctor Id not found");
            jTextField1.setText("");
            jTextField1.requestFocus();
            jTextField2.setText("");
        }
        
        jTextField2.setText(docName);
    }
    
    private String findDoctorName(String docID){
        try(BufferedReader br = new BufferedReader(new FileReader("Doctor.txt"))){
            String line;
            while ((line = br.readLine())!= null){
                String[] parts = line.split("\\|");
                if(parts.length == 6 && parts[0].trim().equalsIgnoreCase(docID)){
                    return parts[2].trim();
                }
            }
        }catch(IOException e){
            e.printStackTrace();
        }
        return null;
    }
    
    private void loadCustomerDoctorFeedback(){
        try(BufferedReader br = new BufferedReader(new FileReader("CustomerFeedbackDoctor.txt"))){
            String line;
            while((line = br.readLine())!=null){
                String[] parts = line.split("\\|");
                if (parts.length == 6){
                    FeedbackDoctor feedback = new FeedbackDoctor(
                            parts[0].trim(),
                            parts[1].trim(),
                            parts[2].trim(),
                            parts[3].trim(),
                            parts[4].trim(),
                            parts[5].trim()
                    );
                    
                    if(feedback.getCusID().equals(customer.getId())) {
                        model.addRow(new Object[]{feedback.getDocID(), feedback.getDocName(), feedback.getDate(), feedback.getComment()});
                    }
                }
            }
        }catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void setupTableRowListener(){
        jTable1.addMouseListener(new java.awt.event.MouseAdapter(){
            public void mouseClicked(java.awt.event.MouseEvent evt){
                int selectedRow = jTable1.getSelectedRow();
                if(selectedRow != -1){
                    String docID = jTable1.getValueAt(selectedRow, 0).toString();
                    String docName = jTable1.getValueAt(selectedRow, 1).toString();
                    String dateStr = jTable1.getValueAt(selectedRow, 2).toString();
                    String comment = jTable1.getValueAt(selectedRow, 3).toString();
                    
                    jTextField1.setText(docID);
                    jTextField2.setText(docName);
                    
                    try{
                        Date date = new SimpleDateFormat("dd-MM-yyyy").parse(dateStr);
                        jDateChooser1.setDate(date);
                    }catch(java.text.ParseException e){
                        e.printStackTrace();
                        jDateChooser1.setDate(null);
                    }
                    
                    jTextField3.setText(comment);
                }
            }
        });
    }
    

    
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
