/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import apumedicalcenter.Manager;
import apumedicalcenter.Staff;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import javax.swing.JTable;

/**
 *
 * @author Sheng Jie
 */
public class Manage_Staff_Page extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Manage_Staff_Page.class.getName());

    /**
     * Creates new form Manage_Staff_Page
     */
    public Manage_Staff_Page() {
        initComponents();
        setTitle("Manage Staff");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Manager manager = new Manager("M001", "880101-10-1111", "John Manager", "Male", LocalDate.parse("1988-01-01"), "0112345678");
        JTable viewStaffTable = manager.viewAllStaff();
        ViewAllStaffScrollPane.setViewportView(viewStaffTable);
        ButtonGroup genderGroup = new ButtonGroup();
        genderGroup.add(maleButton);
        genderGroup.add(femaleButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        icField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        contactField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        searchIDField = new javax.swing.JTextField();
        ViewAllStaffScrollPane = new javax.swing.JScrollPane();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jDateChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Manage Staff");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Staff ID :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Staff IC : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Staff Name : ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Gender : ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("DOB : ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Contact : ");

        idField.setEditable(false);
        idField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        icField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        nameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        maleButton.setText("Male");
        maleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleButtonActionPerformed(evt);
            }
        });

        femaleButton.setText("Female");

        contactField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Search : ");

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("View All");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(icField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jButton2)
                                .addGap(29, 29, 29)
                                .addComponent(jButton3))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(femaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(ViewAllStaffScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(icField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maleButton)
                            .addComponent(femaleButton)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ViewAllStaffScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(16, 16, 16))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id = idField.getText().trim();
        String ic = icField.getText().trim();
        String name = nameField.getText().trim();
        String gender = maleButton.isSelected() ? maleButton.getText() :
                        (femaleButton.isSelected() ? femaleButton.getText() : "");
        java.util.Date selectedDate = jDateChooser.getDate();
        String contact = contactField.getText().trim();
        
        if (ic.isEmpty() || !ic.matches("\\d{12}")) { // 12 digits only
            JOptionPane.showMessageDialog(this, "IC must be 12 digits.");
            return;
        }

        if (contact.isEmpty() || !contact.matches("\\d{10}")) { // 11 digits only
            JOptionPane.showMessageDialog(this, "Contact number must be 10 digits.");
            return;
        }

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name cannot be empty.");
            return;
         }

        if (gender.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a gender.");
            return;
        }

        if (selectedDate == null) {
            JOptionPane.showMessageDialog(this, "Please select a date of birth.");
            return;
        }
        
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String dob = sdf.format(selectedDate);

        
        Manager manager = new Manager("M001", "880101-10-1111", "John Manager", "Male", LocalDate.parse("1988-01-01"), "0112345678");
        boolean success = manager.createStaff(ic, name, gender, dob, contact);

        if (success) {
            JOptionPane.showMessageDialog(this, "Staff record saved successfully!");
            JTable refreshedTable = manager.viewAllStaff();
            ViewAllStaffScrollPane.setViewportView(refreshedTable);
            // clear fields
            idField.setText("");
            icField.setText("");
            nameField.setText("");
            jDateChooser.getDate();
            contactField.setText("");
            maleButton.setSelected(false);
            femaleButton.setSelected(false);

        } else {
            JOptionPane.showMessageDialog(this, "Failed to save staff record.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Manager manager = new Manager("M001", "880101-10-1111", "John Manager", "Male", LocalDate.parse("1988-01-01"), "0112345678");
        String id = idField.getText().trim();
        boolean success = manager.deleteStaff(id);
        if (success) {
            JTable refreshedTable = manager.viewAllStaff();
            ViewAllStaffScrollPane.setViewportView(refreshedTable);
            JOptionPane.showMessageDialog(this, "Staff record deleted successfully!");
            idField.setText("");
            icField.setText("");
            nameField.setText("");
            jDateChooser.setDate(new java.util.Date());
            contactField.setText("");
            maleButton.setSelected(false);
            femaleButton.setSelected(false);
            searchIDField.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "No staff record found with ID " + id + ".");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String searchId = searchIDField.getText().trim();
        if (searchId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an ID to search.");
            return;
        }

        // create Manager object (or reuse existing one)
        Manager manager = new Manager("M001", "880101-10-1111", "John Manager", "Male", LocalDate.parse("1988-01-01"), "0112345678");

        // get search results table
        JTable searchResultTable = manager.searchStaff(searchId);

        // check if found
        if (searchResultTable.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No record found with ID " + searchId + ".");

            // clear table in scrollpane
            ViewAllStaffScrollPane.setViewportView(new JTable());

            // clear all fields
            idField.setText("");
            icField.setText("");
            nameField.setText("");
            jDateChooser.setDate(new java.util.Date());
            contactField.setText("");
            maleButton.setSelected(false);
            femaleButton.setSelected(false);

        } else {
            // show table in scrollpane
            ViewAllStaffScrollPane.setViewportView(searchResultTable);

            // automatically fill your text fields with the first row (since only one record)
            int row = 0; // first row
            String id = searchResultTable.getValueAt(row, 0).toString();
            String ic = searchResultTable.getValueAt(row, 1).toString();
            String name = searchResultTable.getValueAt(row, 2).toString();
            String gender = searchResultTable.getValueAt(row, 3).toString();
            String dob = searchResultTable.getValueAt(row, 4).toString();
            String contact = searchResultTable.getValueAt(row, 5).toString();

            // set your fields
            idField.setText(id);
            icField.setText(ic);
            nameField.setText(name);
            contactField.setText(contact);
            
            try {
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            java.util.Date date = sdf.parse(dob);
            jDateChooser.setDate(date);
            } catch (java.text.ParseException e) {
                jDateChooser.setDate(new java.util.Date());
            }

            // set gender buttons
            if (gender.equalsIgnoreCase("Male")) {
                maleButton.setSelected(true);
                femaleButton.setSelected(false);
            } else if (gender.equalsIgnoreCase("Female")) {
                femaleButton.setSelected(true);
                maleButton.setSelected(false);
            } else {
                maleButton.setSelected(false);
                femaleButton.setSelected(false);
            }
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Manager manager = new Manager("M001", "880101-10-1111", "John Manager", "Male", LocalDate.parse("1988-01-01"), "0112345678");
        JTable allStaffTable = manager.viewAllStaff();
        ViewAllStaffScrollPane.setViewportView(allStaffTable);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Inside your update button actionPerformed:
        String id = idField.getText().trim();  // id stays the same
        String ic = icField.getText().trim();
        String name = nameField.getText().trim();
        String gender = maleButton.isSelected() ? maleButton.getText() :
                        (femaleButton.isSelected() ? femaleButton.getText() : "");
        java.util.Date selectedDate = jDateChooser.getDate();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String dob = sdf.format(selectedDate);
        String contact = contactField.getText().trim();
        
        if (ic.isEmpty() || !ic.matches("\\d{12}")) { // 12 digits only
        JOptionPane.showMessageDialog(this, "IC must be 12 digits.");
        return;
        }

        if (contact.isEmpty() || !contact.matches("\\d{10}")) { // 11 digits only
            JOptionPane.showMessageDialog(this, "Contact number must be 10 digits.");
            return;
        }

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name cannot be empty.");
            return;
         }

        if (gender.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a gender.");
            return;
        }

        if (selectedDate == null) {
            JOptionPane.showMessageDialog(this, "Please select a date of birth.");
            return;
        }

        // Build Staff object from the fields
        Staff updatedStaff = new Staff(id, ic, name, gender, LocalDate.parse(dob.trim()), contact);

        // Create Manager object (or reuse existing one)
        Manager manager = new Manager("M001", "880101-10-1111", "John Manager", "Male", LocalDate.parse("1988-01-01"), "0112345678");

        // Call editStaff
        boolean success = manager.editStaff(updatedStaff);

        if (success) {
            JOptionPane.showMessageDialog(this, "Staff record updated successfully!");
            // Optionally refresh the table:
            JTable allStaffTable = manager.viewAllStaff();
            ViewAllStaffScrollPane.setViewportView(allStaffTable);
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update staff record.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Manage_User_Page page = new Manage_User_Page();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void contactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ViewAllStaffScrollPane;
    private javax.swing.JTextField contactField;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JTextField icField;
    private javax.swing.JTextField idField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField searchIDField;
    // End of variables declaration//GEN-END:variables
}
