/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import apumedicalcenter.Customer;
import apumedicalcenter.Doctor;
import apumedicalcenter.History;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author tatsu
 */
public class StaffViewCharges extends javax.swing.JFrame {
    
    private final StaffMainMenuPage mainMenu;
    
    private DefaultTableModel model = new DefaultTableModel();
    private String[] columnName = {"Customer ID","Customer Name","Date","Time","Charges(RM)","Doctor's Feedback"};

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffViewCharges.class.getName());


    public StaffViewCharges(StaffMainMenuPage mainMenu) {
        this.mainMenu = mainMenu;
        initComponents();
        setTitle("Charges & Feedback");
        setLocationRelativeTo(null);
        model.setColumnIdentifiers(columnName);
        jTable1.setModel(model);
        
        loadFeedback();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Feedback & Charges");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Back To Main Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainMenu.setVisible(true);  
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loadFeedback() {
        try (BufferedReader br = new BufferedReader(new FileReader("History.txt"))){
            String line;
            br.readLine();
            while ((line = br.readLine())!=null){
                String[] parts = line.split("\\|");
                if(parts.length == 8){
                    Customer c = new Customer(parts[0].trim(), parts[1].trim()); 
                    Doctor d = new Doctor(parts[4].trim(), parts[5].trim());
                    
                    History his = new History(
                            c,
                            d,
                            parts[2].trim(),
                            parts[3].trim(),
                            parts[6].trim(),
                            parts[7].trim()        
                    );
                
                    model.addRow(new Object[]{
                        his.getCustomer().getId(),
                        his.getCustomer().getName(),
                        his.getDate(),
                        his.getTime(),
                        his.getCharges(),
                        his.getFeedback(),
                    });
                }
            }
        }catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error loading feedback data: " + e.getMessage());
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
