/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import GUI.Main_Page;
import apumedicalcenter.Manager;
import java.time.LocalDate;
import javax.swing.JTable;

/**
 *
 * @author Sheng Jie
 */
public class View_Appointment_Page extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(View_Appointment_Page.class.getName());

    /**
     * Creates new form View_Appointment_Page
     */
    public View_Appointment_Page() {
            initComponents();
            setTitle("View Appointment");
            setLocationRelativeTo(null);
            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setupTable();
            loadAppointments();  
            Manager manager = new Manager("M001", "880101-10-1111", "John Manager", "Male", LocalDate.parse("1988-01-01"), "0112345678");
            JTable viewDoctorFeedbackTable = manager.viewDoctorFeedback();
            jTable2.setModel(viewDoctorFeedbackTable.getModel());
        }

        private static final String APPT_FILE = "Appointments.txt";
        private static final String[] COLS = {
            "Cus.name", "Cus.ID", "Date", "Time", "Doc.ID", "Doc.Name", "Reason"
        };

        private void setupTable() {
            javax.swing.table.DefaultTableModel m = new javax.swing.table.DefaultTableModel(COLS, 0) {
                @Override public boolean isCellEditable(int r, int c) { return false; }
            };
            jTable1.setModel(m);
            jTable1.setAutoCreateRowSorter(true); 
        }

        private void loadAppointments() {
            javax.swing.table.DefaultTableModel m = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            m.setRowCount(0);

            java.io.File f = new java.io.File(APPT_FILE);
            if (!f.exists()) return;

        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(f))) {
            String line;
            while ((line = br.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty()) continue;
                String[] d = line.split("\\|", -1);

                if (d.length == 7) {
                    m.addRow(new Object[]{ d[0].trim(), d[1].trim(), d[2].trim(), d[3].trim(),
                                           d[4].trim(), d[5].trim(), d[6].trim() });
                } else if (d.length == 6) {
                    String docField = d[4].trim();
                    String docId = docField, docName = "";
                    int idx = docField.indexOf('(');
                    if (idx >= 0 && docField.endsWith(")") && idx > 0) {
                        docId = docField.substring(0, idx);
                        docName = docField.substring(idx + 1, docField.length() - 1);
                    }
                    m.addRow(new Object[]{ d[0].trim(), d[1].trim(), d[2].trim(), d[3].trim(),
                                           docId, docName, d[5].trim() });
                } 
            }
        } 
        catch (java.io.IOException ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Failed to load appointments: " + ex.getMessage(),
                    "I/O Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }


        public void refreshTable() {
            loadAppointments();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("View Appointment");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane1.addTab("Pending Appointment", jScrollPane1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTabbedPane1.addTab("Past Appointment", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(571, 571, 571))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Main_Page page = new Main_Page();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
